# Generated by Django 4.2.6 on 2023-10-22 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('roll_number', models.IntegerField(db_index=True, unique=True)),
                ('standard', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_number', models.IntegerField(null=True)),
                ('subject_name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('roll_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='studentrecords.students', to_field='roll_number', verbose_name='student_roll_number')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='studentrecords.subjects', verbose_name='student_roll_number')),
            ],
            options={
                'db_table': 'marksheet',
            },
        ),
    ]
